'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={get:k=>{try{return localStorage.getItem(k)}catch{return null}},set:(k,v)=>{try{localStorage.setItem(k,v);return true}catch{return false}},remove:k=>{try{localStorage.removeItem(k)}catch{}}};
const assetUri=p=>window.__THE_SECRET_ASSETS__?.[p]||p;
const clean=s=>String(s??'').replace(/<script[\s\S]*?>[\s\S]*?<\/script>/gi,'');
async function getJSON(path){const r=await fetch(path);if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.json()}
function hydrateAssets(){$$('[data-asset-src]').forEach(el=>el.src=assetUri(el.dataset.assetSrc));$$('[data-asset-srcset]').forEach(el=>el.srcset=assetUri(el.dataset.assetSrcset));}
function sourceLabel(t){return ({'whatsapp-evidence':'From our conversation','documented-archive':'Documented archive','user-recollection':'A memory I carry','reconstructed-reflection':'What it meant to me'})[t]||'Context'}
function setupOpening(){const gate=$('#openingGate');if(!gate)return;if(store.get('the-secret-skip-intro')==='true'){gate.remove();document.body.classList.remove('intro-locked');return}const leave=target=>{document.body.classList.remove('intro-locked');gate.classList.add('opening-gate-leaving');setTimeout(()=>{gate.remove();target&&$(target)?.scrollIntoView({behavior:'smooth'})},420)};$('#enterExperience')?.addEventListener('click',()=>leave('#opening'));$('#exploreExperience')?.addEventListener('click',()=>leave('#letter'));$('#skipIntro')?.addEventListener('click',()=>{store.set('the-secret-skip-intro','true');leave('#opening')})}
function setupStoryProgress(){const scenes=$$('[data-story-step]'),label=$('#storyStepLabel'),dots=$$('.story-dots i'),next=$('#headerNext');if(!scenes.length||!label)return;const setActive=s=>{const n=Number(s.dataset.storyStep||1);label.textContent=`${n} of ${scenes.length} · ${s.dataset.stepName||'Story'}`;dots.forEach((d,i)=>d.classList.toggle('active',i===n-1));if(next){const target=scenes[Math.min(n,scenes.length-1)];next.href=n>=scenes.length?'#letter':`#${target.id}`;next.textContent=n>=scenes.length?'Letter':'Next'}};let ticking=false;const update=()=>{const marker=innerHeight*.35;let active=scenes[0],best=Infinity;for(const s of scenes){const r=s.getBoundingClientRect();if(r.top<=marker&&r.bottom>marker){active=s;break}const d=Math.abs(r.top-marker);if(d<best){best=d;active=s}}setActive(active);ticking=false};addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(update)}},{passive:true});addEventListener('resize',update);update()}
function setupReadingProgress(){const bar=$('#readingProgressBar');if(!bar)return;const update=()=>{const d=document.documentElement,max=d.scrollHeight-d.clientHeight;bar.style.width=`${max?Math.min(100,d.scrollTop/max*100):0}%`};addEventListener('scroll',update,{passive:true});update()}
function setupMotion(){const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,nodes=$$('.motion-enter,.story-bridge');if(reduce||!('IntersectionObserver'in window))nodes.forEach(n=>n.classList.add('is-motion-visible','is-visible'));else{const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('is-motion-visible','is-visible')}),{threshold:.16});nodes.forEach(n=>o.observe(n))}if(!reduce){const media=$$('[data-parallax]');let t=false;const paint=()=>{media.forEach(m=>{const h=m.closest('.parallax-stage');if(!h)return;const r=h.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;const f=Number(m.dataset.parallax||.08),off=(r.top+r.height/2)-innerHeight/2;m.style.setProperty('--parallax-y',`${Math.max(-28,Math.min(28,-off*f)).toFixed(1)}px`)});t=false};addEventListener('scroll',()=>{if(!t){t=true;requestAnimationFrame(paint)}},{passive:true});paint()}}
function setupLetterMemory(){const trigger=$('#letterMemoryTrigger'),dialog=$('#letterMemoryDialog'),close=$('#letterMemoryClose'),cont=$('#continueToLetter');if(!trigger||!dialog)return;const open=()=>{typeof dialog.showModal==='function'?dialog.showModal():dialog.setAttribute('open','');if(cont){cont.classList.remove('is-locked');cont.removeAttribute('aria-disabled');cont.textContent='Continue to the letter';cont.href='#letter'}};trigger.addEventListener('click',open);close?.addEventListener('click',()=>dialog.close?.());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close?.()});cont?.addEventListener('click',e=>{if(cont.getAttribute('aria-disabled')==='true')e.preventDefault()})}
async function applyManifestImages(){try{const m=await getJSON('image-manifest.json');$$('[data-image-key]').forEach(slot=>{const item=m[slot.dataset.imageKey],img=slot.querySelector('img');if(!item||!img)return;img.src=assetUri(item.src);img.alt=item.alt||'';img.hidden=false;slot.classList.add('has-image');slot.querySelector('.slot-label')?.setAttribute('hidden','')})}catch(e){console.warn('Image manifest unavailable',e)}}
let chapters=[],chapter=0;
function renderChapter(i){if(!chapters.length)return;chapter=(i+chapters.length)%chapters.length;const c=chapters[chapter];$('#actLabel').textContent=`${c.label||c.act||`Act ${chapter+1}`} · ${sourceLabel(c.sourceType)}`;$('#actTitle').textContent=c.title||'';$('#letterBody').innerHTML=(c.prose||[]).map(p=>`<p>${clean(p)}</p>`).join('');$('#letterScripture').textContent=c.scripture||'';$('#chapterProgress').textContent=`${chapter+1} of ${chapters.length}`;$$('.chapter-btn').forEach((b,x)=>b.classList.toggle('active',x===chapter));$('#prevChapter').disabled=chapter===0;$('#nextChapter').textContent=chapter===chapters.length-1?'Return to first act ↺':'Next →';store.set('the-secret-last-chapter',chapter)}
function setupChapters(data){chapters=data.chapters||data.acts||[];const host=$('#chapterList');if(!host||!chapters.length)return;host.innerHTML='';chapters.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.className='chapter-btn';b.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span><strong>${clean(c.title)}</strong>`;b.onclick=()=>renderChapter(i);host.appendChild(b)});$('#prevChapter').onclick=()=>renderChapter(chapter-1);$('#nextChapter').onclick=()=>renderChapter(chapter===chapters.length-1?0:chapter+1);const saved=Number(store.get('the-secret-last-chapter'));renderChapter(Number.isInteger(saved)&&saved>=0&&saved<chapters.length?saved:0)}
let tracks=[],track=0,mood='all',search='';
const spotifySearch=t=>`https://open.spotify.com/search/${encodeURIComponent(`${t.title} ${t.artist}`)}`;
function filteredTracks(){return tracks.filter(t=>(mood==='all'||t.mood===mood)&&`${t.title} ${t.artist}`.toLowerCase().includes(search))}
function showTrack(i,open=false){if(!tracks.length)return;track=(i+tracks.length)%tracks.length;const t=tracks[track];$('#trackTitle').textContent=t.title;$('#trackArtist').textContent=t.artist;const link=$('#externalTrackLink'),url=t.externalUrl||spotifySearch(t);if(link){link.href=url;link.hidden=false}$('#audioStatus').textContent='This Preview opens songs on Spotify instead of hosting audio.';$$('.track-btn').forEach(b=>b.classList.toggle('active',Number(b.dataset.index)===track));store.set('the-secret-last-track',track);if(open)window.open(url,'_blank','noopener')}
function renderTracks(){const host=$('#playlist');if(!host)return;host.innerHTML='';const list=filteredTracks();list.forEach(t=>{const i=tracks.indexOf(t),b=document.createElement('button');b.type='button';b.className='track-btn';b.dataset.index=i;b.innerHTML=`<span class="track-index">${String(i+1).padStart(2,'0')}</span><span class="track-copy"><span>${clean(t.title)}</span><small>${clean(t.artist)}</small></span><span class="track-date">${clean(t.date||'')}</span>`;b.onclick=()=>showTrack(i,true);host.appendChild(b)});$('#trackCount').textContent=`${list.length} ${list.length===1?'track':'tracks'}`}
function setupTracks(db){const phases=['beginning','fracture','faith','return'];tracks=Object.entries(db).map(([file,d],i)=>({file,title:d.title||file.replace(/\.mp3$/,'').replaceAll('-',' '),artist:d.artist||'The Secret',date:d.date||'',mood:d.journeyPhase||phases[Math.min(3,Math.floor(i/Math.max(1,Math.ceil(Object.keys(db).length/4))))],externalUrl:d.externalUrl||''}));renderTracks();showTrack(Number(store.get('the-secret-last-track'))||0);$('#trackSearch')?.addEventListener('input',e=>{search=e.target.value.trim().toLowerCase();renderTracks()});$$('.mood-btn').forEach(b=>b.onclick=()=>{mood=b.dataset.mood;$$('.mood-btn').forEach(x=>x.classList.toggle('active',x===b));renderTracks()});$('#prevBtn').onclick=()=>showTrack(track-1);$('#nextBtn').onclick=()=>showTrack(track+1)}
function setupReflection(){const f=$('#reflectionText'),s=$('#reflectionStatus');if(!f)return;f.value=store.get('the-secret-reflection')||'';$('#saveReflection').onclick=()=>{store.set('the-secret-reflection',f.value);s.textContent='Reflection saved on this device.'};$('#clearReflection').onclick=()=>{f.value='';store.remove('the-secret-reflection');s.textContent='Reflection cleared.'};$('#exportPrivateData')?.addEventListener('click',()=>{const payload={exportedAt:new Date().toISOString(),reflection:f.value,herSpace:{}};$$('[data-her-memory]').forEach(el=>payload.herSpace[el.dataset.herMemory]=el.value);const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='the-secret-private-text.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)})}
function renderMemories(items=[]){const host=$('#memoryTimeline'),prompts=$('#herPrompts');if(!host||!prompts)return;host.innerHTML='';prompts.innerHTML='';items.forEach(m=>{const a=document.createElement('article');a.className='memory-story-card';a.innerHTML=`<p class="source-chip">${sourceLabel(m.sourceType)}</p><h3>${clean(m.title)}</h3><p>${clean(m.summary)}</p>`;host.appendChild(a);const l=document.createElement('label');l.className='her-prompt-card';l.innerHTML=`<strong>${clean(m.title)}</strong><span>${clean(m.herPrompt||'How do you remember this?')}</span><textarea rows="4" data-her-memory="${clean(m.id)}" placeholder="Your memory, only if you choose..."></textarea><button type="button" class="text-btn">Save on this device</button><small></small>`;const ta=l.querySelector('textarea'),status=l.querySelector('small');ta.value=store.get(`the-secret-her-${m.id}`)||'';l.querySelector('button').onclick=()=>{store.set(`the-secret-her-${m.id}`,ta.value);status.textContent='Saved locally.'};prompts.appendChild(l)})}
function setupVoice(){const start=$('#startRecording'),stop=$('#stopRecording'),status=$('#recordStatus'),player=$('#voicePlayer');if(!start||!stop)return;let rec,stream,chunks=[];start.onclick=async()=>{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){status.textContent='Recording is not supported in this browser.';return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(stream);chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'}),url=URL.createObjectURL(blob);player.src=url;$('#voiceTitle').textContent=$('#recordingTitle').value.trim()||'Voice note';$('#voiceMeta').textContent='Recorded on this device';status.textContent='Recorded for this session.';stream.getTracks().forEach(t=>t.stop());start.disabled=false;stop.disabled=true};rec.start();start.disabled=true;stop.disabled=false;status.textContent='Recording…'}catch{status.textContent='Microphone access was not granted.'}};stop.onclick=()=>rec?.state==='recording'&&rec.stop()}
async function init(){hydrateAssets();setupOpening();setupStoryProgress();setupReadingProgress();setupMotion();setupLetterMemory();setupReflection();setupVoice();applyManifestImages();try{const [exp,db]=await Promise.all([getJSON('experience.json'),getJSON('track-database.json')]);setupChapters(exp);renderMemories(exp.memories||[]);setupTracks(db)}catch(e){console.error(e);document.body.insertAdjacentHTML('afterbegin','<div class="load-error">Some story data could not load. Refresh this Preview.</div>')}}
document.addEventListener('DOMContentLoaded',init);
